clc; clear; close all;

%% 1. HARITA VE GÖRSELLEŞTIRME
modelFile = 'map (3).osm';
viewer = siteviewer("Buildings", modelFile);

% Kampüs sınırı
lat_sinir = [39.8870, 39.8860, 39.8780, 39.8680, 39.8680, 39.8750, 39.8870];
lon_sinir = [33.4410, 33.4560, 33.4580, 33.4550, 33.4480, 33.4380, 33.4410];
pgon = geopolyshape(lat_sinir, lon_sinir);

% Coğrafi eksen oluşturma ve doğru çizim fonksiyonu
gx = geoaxes;
geoplot(gx, pgon); 

%% 2. SİNC ÖRÜNTÜLÜ SEKTÖREL ANTEN TANIMLA
fc = 1.8e9;  % Frekans>
lambda = 3e8/fc;

% Yatayda 65°, dikeyde 10° huzme genişliği (Hata veren parametreler temizlendi)
sectorAnt = phased.SincAntennaElement(...
    'Beamwidth', [65, 10]); 

%% 3. BAZ İSTASYONLARI
tx1 = txsite(...
    "Name", "Tx1_Kuzey", ...
    "Latitude", 39.883654, ...
    "Longitude", 33.445044, ...
    "AntennaHeight", 30, ...
    "TransmitterPower", 43, ...  
    "TransmitterFrequency", fc, ...
    "Antenna", sectorAnt, ...
    "AntennaAngle", [180; -6]);  

tx2 = txsite(...
    "Name", "Tx2_Orta", ...
    "Latitude", 39.878568, ...
    "Longitude", 33.448944, ...
    "AntennaHeight", 30, ...
    "TransmitterPower", 43, ...
    "TransmitterFrequency", fc, ...
    "Antenna", sectorAnt, ...
    "AntennaAngle", [270; -6]);

tx3 = txsite(...
    "Name", "Tx3_Guney", ...
    "Latitude", 39.871768, ...
    "Longitude", 33.451413, ...
    "AntennaHeight", 30, ...
    "TransmitterPower", 43, ...
    "TransmitterFrequency", fc, ...
    "Antenna", sectorAnt, ...
    "AntennaAngle", [45; -6]);

tx_array = [tx1, tx2, tx3];
show(tx_array);

%% 4. ALICI GRİDİ (2500 nokta)
[lat_grid, lon_grid] = meshgrid(...
    linspace(39.868, 39.887, 50), ...
    linspace(33.438, 33.458, 50));

rx_grid = rxsite(...
    'Latitude', lat_grid(:), ...
    'Longitude', lon_grid(:), ...
    'AntennaHeight', 1.5);

%% 5. RAY TRACING MODELİ (Sürüm uyumsuzluğu yaratan GPU parametresi kaldırıldı)
pm = propagationModel("raytracing", ...
    "Method", "sbr", ...
    "MaxNumReflections", 3, ...  
    "MaxNumDiffractions", 1, ...
    "SurfaceMaterial", "concrete", ...
    "MaxAbsolutePathLoss", 140, ...  
    "AngularSeparation", 1);

%% 6. LTE PARAMETRELERİ
bandwidth = 20e6;  % 20 MHz
noiseFigure = 7;   % dB
noisePower = -174 + 10*log10(bandwidth) + noiseFigure;  % -100.99 dBm

%% 7. SINR HARİTASI (LTE parametreleriyle)
disp('SINR Haritası hesaplanıyor...');
sinr(tx_array, pm, ...
    'Resolution', 10, ...  % 10 metre çözünürlük
    'ReceiverNoisePower', noisePower, ...
    'ReceiverGain', 0, ...  % UE anten gain
    'MaxRange', 2000);  % 2 km max menzil

%% 8. RSRP HESAPLAisI (LTE KPI)
disp('RSRP hesaplanıyor...');
rsrp_values = sigstrength(rx_grid, tx_array, pm);

% RSRP kategorileri (3GPP TS 36.133)
excellent = rsrp_values > -80;  % Mükemmel
good = rsrp_values > -90 & rsrp_values <= -80;  % İyi
fair = rsrp_values > -100 & rsrp_values <= -90;  % Orta
poor = rsrp_values <= -100;  % Zayıf

fprintf('RSRP İstatistikleri:\n');
fprintf('Mükemmel (>-80 dBm): %.1f%%\n', 100*sum(excellent)/length(rsrp_values));
fprintf('İyi (-90 to -80 dBm): %.1f%%\n', 100*sum(good)/length(rsrp_values));
fprintf('Orta (-100 to -90 dBm): %.1f%%\n', 100*sum(fair)/length(rsrp_values));
fprintf('Zayıf (<-100 dBm): %.1f%%\n', 100*sum(poor)/length(rsrp_values));

%% 9. THROUGHPUT TAHMİNİ (Shannon Capacity)
% C = BW × log2(1 + SINR_linear)
sinr_linear = 10.^(rsrp_values/10);
capacity_mbps = (bandwidth/1e6) * log2(1 + sinr_linear);

fprintf('\nOrtalama Kapasite: %.2f Mbps\n', mean(capacity_mbps));
fprintf('Max Kapasite: %.2f Mbps\n', max(capacity_mbps));

%% 10. RAY TRACING GÖRSELLEŞTİRME (Seçili noktalar)
disp('Ray tracing görselleştirme...');
% Grid'den 10 rastgele nokta seç
selected_idx = randperm(length(rx_grid), 10);
rx_selected = rx_grid(selected_idx);
raytrace(tx_array, rx_selected, pm);

disp('✅ Simülasyon tamamlandı!');
